### ISSUE TITLE
docs failing

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#456]
ReadTheDocs builds have been failing since Oct. 27. The error produced is not helpful (but is included below). Unfortunately the docs build successfully on quartz.

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: 12 added, 0 changed, 0 removed
reading sources... [  8%] index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/transforms/references.py", line 38, in apply
    domain.process_doc(self.env, self.env.docname, self.document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/domains/std.py", line 586, in process_doc
    self.note_labels(env, docname, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object has no attribute '__getitem__'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/scr/envs/latest/lib/python2.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object has no attribute '__getitem__'
The full traceback has been saved in /tmp/sphinx-err-XHTM_q.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by CamStan** [comment]
Looking at others who have had this issue. It appears the issue started with docutils v0.18, which our build uses:
```
Collecting docutils>=0.11
  Downloading docutils-0.18-py2.py3-none-any.whl (569 kB)
```
It appears the solution is to cap the version; `docutils<0.18`, and we could probably update the version of python as well.

Error description: https://github.com/readthedocs/readthedocs.org/issues/8616
Documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file
